export type SalesCallListRow = {
  id: string;
  notes: string | null;
  callDate: string | null;
  leadNotionPageId: string | null;
  leadName: string | null;
  leadEmail: string | null;
  userId: string | null;
  outcome: string | null;
  salesMechanism: string | null;
  callLength: number | null;
  ranking: string | null;
  course: string | null;
  delivery: string | null;
  tutorSelect: string | null;
  tutorPersonId: string | null;
  showUp: boolean;
  offer: boolean;
  closed: boolean;
  paymentMade: boolean;
  paymentDate: string | null;
  cashOnCall: number | null;
  paidAfterwards: number | null;
  outstandingBalance: number | null;
  status: string | null;
  commissionAmount: number | null;
  commissionPaid: boolean;
  commissionValid: boolean;
  calendarInvite: boolean;
  welcomeEmail: boolean;
  whatsappChatMade: boolean;
  scheduleWhatsappGroup: boolean;
  tutorNotified: boolean;
  timeAssigned: boolean;
  packageCreated: boolean;
  offboarded: boolean;
  offboarded1: boolean;
  notionPageId: string | null;
  notionSyncStatus: string;
  notionSyncError: string | null;
  updatedAt: string;
};

export type NotionLeadCacheOption = {
  notionPageId: string;
  name: string | null;
  email: string | null;
  phone: string | null;
};

export type SalesCallWriteInput = {
  notes?: string | null;
  callDate?: string | null;
  leadNotionPageId?: string | null;
  outcome?: string | null;
  salesMechanism?: string | null;
  callLength?: number | null;
  ranking?: string | null;
  course?: string | null;
  delivery?: string | null;
  tutorSelect?: string | null;
  tutorPersonId?: string | null;
  showUp?: boolean;
  offer?: boolean;
  closed?: boolean;
  paymentMade?: boolean;
  paymentDate?: string | null;
  cashOnCall?: number | null;
  paidAfterwards?: number | null;
  outstandingBalance?: number | null;
  status?: string | null;
  commissionAmount?: number | null;
  commissionPaid?: boolean;
  commissionValid?: boolean;
  calendarInvite?: boolean;
  welcomeEmail?: boolean;
  whatsappChatMade?: boolean;
  scheduleWhatsappGroup?: boolean;
  tutorNotified?: boolean;
  timeAssigned?: boolean;
  packageCreated?: boolean;
  offboarded?: boolean;
  offboarded1?: boolean;
};
